import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    MONGO_CONNECTION_STRING  = os.getenv("MONGO_CONNECTION_STRING")
    GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
    ANTHROPIC_API_KEY=os.getenv("ANTHROPIC_API_KEY")
    NOVU_API_KEY= os.getenv("NOVU_API_KEY")
    NOVU_TRIGGER_URL=os.getenv("NOVU_TRIGGER_URL")
    SUBSCRIBER_ID=os.getenv("SUBSCRIBER_ID")
    SECRET_KEY=os.getenv("SECRET_KEY")
    AWS_ACCESS_KEY=os.getenv("AWS_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_REGION=os.getenv("AWS_REGION")
    AWS_S3_BUCKET_NAME=os.getenv("AWS_S3_BUCKET_NAME")

    AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY

    BEDROCK_MODEL_ARN = os.getenv('BEDROCK_MODEL_ARN')
    AZURE_SUBSCRIPTION_KEY=os.getenv("AZURE_SUBSCRIPTION_KEY")